// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/supanadit/forge/domain"
)

// BuildRepository is an autogenerated mock type for the BuildRepository type
type BuildRepository struct {
	mock.Mock
}

type BuildRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BuildRepository) EXPECT() *BuildRepository_Expecter {
	return &BuildRepository_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: ctx, spec, sourceDir, env
func (_m *BuildRepository) Build(ctx context.Context, spec domain.BuildSpec, sourceDir string, env []string) (string, error) {
	ret := _m.Called(ctx, spec, sourceDir, env)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BuildSpec, string, []string) (string, error)); ok {
		return rf(ctx, spec, sourceDir, env)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BuildSpec, string, []string) string); ok {
		r0 = rf(ctx, spec, sourceDir, env)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BuildSpec, string, []string) error); ok {
		r1 = rf(ctx, spec, sourceDir, env)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuildRepository_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type BuildRepository_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - spec domain.BuildSpec
//   - sourceDir string
//   - env []string
func (_e *BuildRepository_Expecter) Build(ctx interface{}, spec interface{}, sourceDir interface{}, env interface{}) *BuildRepository_Build_Call {
	return &BuildRepository_Build_Call{Call: _e.mock.On("Build", ctx, spec, sourceDir, env)}
}

func (_c *BuildRepository_Build_Call) Run(run func(ctx context.Context, spec domain.BuildSpec, sourceDir string, env []string)) *BuildRepository_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.BuildSpec), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *BuildRepository_Build_Call) Return(buildDir string, err error) *BuildRepository_Build_Call {
	_c.Call.Return(buildDir, err)
	return _c
}

func (_c *BuildRepository_Build_Call) RunAndReturn(run func(context.Context, domain.BuildSpec, string, []string) (string, error)) *BuildRepository_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function with given fields: ctx, buildDir, spec, verbose
func (_m *BuildRepository) Install(ctx context.Context, buildDir string, spec domain.BuildSpec, verbose bool) error {
	ret := _m.Called(ctx, buildDir, spec, verbose)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BuildSpec, bool) error); ok {
		r0 = rf(ctx, buildDir, spec, verbose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuildRepository_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type BuildRepository_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - buildDir string
//   - spec domain.BuildSpec
//   - verbose bool
func (_e *BuildRepository_Expecter) Install(ctx interface{}, buildDir interface{}, spec interface{}, verbose interface{}) *BuildRepository_Install_Call {
	return &BuildRepository_Install_Call{Call: _e.mock.On("Install", ctx, buildDir, spec, verbose)}
}

func (_c *BuildRepository_Install_Call) Run(run func(ctx context.Context, buildDir string, spec domain.BuildSpec, verbose bool)) *BuildRepository_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.BuildSpec), args[3].(bool))
	})
	return _c
}

func (_c *BuildRepository_Install_Call) Return(_a0 error) *BuildRepository_Install_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BuildRepository_Install_Call) RunAndReturn(run func(context.Context, string, domain.BuildSpec, bool) error) *BuildRepository_Install_Call {
	_c.Call.Return(run)
	return _c
}

// NewBuildRepository creates a new instance of BuildRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuildRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuildRepository {
	mock := &BuildRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
