// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/supanadit/forge/domain"
)

// BuildService is an autogenerated mock type for the BuildService type
type BuildService struct {
	mock.Mock
}

type BuildService_Expecter struct {
	mock *mock.Mock
}

func (_m *BuildService) EXPECT() *BuildService_Expecter {
	return &BuildService_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: ctx, manifestPath, opts
func (_m *BuildService) Build(ctx context.Context, manifestPath string, opts domain.BuildOptions) (domain.BuildResult, error) {
	ret := _m.Called(ctx, manifestPath, opts)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 domain.BuildResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BuildOptions) (domain.BuildResult, error)); ok {
		return rf(ctx, manifestPath, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BuildOptions) domain.BuildResult); ok {
		r0 = rf(ctx, manifestPath, opts)
	} else {
		r0 = ret.Get(0).(domain.BuildResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.BuildOptions) error); ok {
		r1 = rf(ctx, manifestPath, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuildService_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type BuildService_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - manifestPath string
//   - opts domain.BuildOptions
func (_e *BuildService_Expecter) Build(ctx interface{}, manifestPath interface{}, opts interface{}) *BuildService_Build_Call {
	return &BuildService_Build_Call{Call: _e.mock.On("Build", ctx, manifestPath, opts)}
}

func (_c *BuildService_Build_Call) Run(run func(ctx context.Context, manifestPath string, opts domain.BuildOptions)) *BuildService_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.BuildOptions))
	})
	return _c
}

func (_c *BuildService_Build_Call) Return(_a0 domain.BuildResult, _a1 error) *BuildService_Build_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BuildService_Build_Call) RunAndReturn(run func(context.Context, string, domain.BuildOptions) (domain.BuildResult, error)) *BuildService_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewBuildService creates a new instance of BuildService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuildService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuildService {
	mock := &BuildService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
