// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CacheCleaner is an autogenerated mock type for the CacheCleaner type
type CacheCleaner struct {
	mock.Mock
}

type CacheCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheCleaner) EXPECT() *CacheCleaner_Expecter {
	return &CacheCleaner_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: project
func (_m *CacheCleaner) List(project string) ([]string, error) {
	ret := _m.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(project)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheCleaner_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CacheCleaner_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - project string
func (_e *CacheCleaner_Expecter) List(project interface{}) *CacheCleaner_List_Call {
	return &CacheCleaner_List_Call{Call: _e.mock.On("List", project)}
}

func (_c *CacheCleaner_List_Call) Run(run func(project string)) *CacheCleaner_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CacheCleaner_List_Call) Return(_a0 []string, _a1 error) *CacheCleaner_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheCleaner_List_Call) RunAndReturn(run func(string) ([]string, error)) *CacheCleaner_List_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function with given fields: project, validSteps
func (_m *CacheCleaner) Prune(project string, validSteps map[string]bool) error {
	ret := _m.Called(project, validSteps)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]bool) error); ok {
		r0 = rf(project, validSteps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheCleaner_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type CacheCleaner_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - project string
//   - validSteps map[string]bool
func (_e *CacheCleaner_Expecter) Prune(project interface{}, validSteps interface{}) *CacheCleaner_Prune_Call {
	return &CacheCleaner_Prune_Call{Call: _e.mock.On("Prune", project, validSteps)}
}

func (_c *CacheCleaner_Prune_Call) Run(run func(project string, validSteps map[string]bool)) *CacheCleaner_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]bool))
	})
	return _c
}

func (_c *CacheCleaner_Prune_Call) Return(_a0 error) *CacheCleaner_Prune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheCleaner_Prune_Call) RunAndReturn(run func(string, map[string]bool) error) *CacheCleaner_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// NewCacheCleaner creates a new instance of CacheCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheCleaner {
	mock := &CacheCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
