// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/supanadit/forge/domain"
)

// ValidateService is an autogenerated mock type for the ValidateService type
type ValidateService struct {
	mock.Mock
}

type ValidateService_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidateService) EXPECT() *ValidateService_Expecter {
	return &ValidateService_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx, manifestPath
func (_m *ValidateService) Validate(ctx context.Context, manifestPath string) (domain.ValidationResult, error) {
	ret := _m.Called(ctx, manifestPath)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 domain.ValidationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ValidationResult, error)); ok {
		return rf(ctx, manifestPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ValidationResult); ok {
		r0 = rf(ctx, manifestPath)
	} else {
		r0 = ret.Get(0).(domain.ValidationResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, manifestPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ValidateService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - manifestPath string
func (_e *ValidateService_Expecter) Validate(ctx interface{}, manifestPath interface{}) *ValidateService_Validate_Call {
	return &ValidateService_Validate_Call{Call: _e.mock.On("Validate", ctx, manifestPath)}
}

func (_c *ValidateService_Validate_Call) Run(run func(ctx context.Context, manifestPath string)) *ValidateService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ValidateService_Validate_Call) Return(_a0 domain.ValidationResult, _a1 error) *ValidateService_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ValidateService_Validate_Call) RunAndReturn(run func(context.Context, string) (domain.ValidationResult, error)) *ValidateService_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidateService creates a new instance of ValidateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateService {
	mock := &ValidateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
