// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/supanadit/forge/domain"

	mock "github.com/stretchr/testify/mock"
)

// FetchRepository is an autogenerated mock type for the FetchRepository type
type FetchRepository struct {
	mock.Mock
}

type FetchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FetchRepository) EXPECT() *FetchRepository_Expecter {
	return &FetchRepository_Expecter{mock: &_m.Mock}
}

// FetchArchive provides a mock function with given fields: ctx, spec
func (_m *FetchRepository) FetchArchive(ctx context.Context, spec domain.ArchiveFetch) (string, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FetchArchive")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArchiveFetch) (string, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArchiveFetch) string); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ArchiveFetch) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchRepository_FetchArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArchive'
type FetchRepository_FetchArchive_Call struct {
	*mock.Call
}

// FetchArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - spec domain.ArchiveFetch
func (_e *FetchRepository_Expecter) FetchArchive(ctx interface{}, spec interface{}) *FetchRepository_FetchArchive_Call {
	return &FetchRepository_FetchArchive_Call{Call: _e.mock.On("FetchArchive", ctx, spec)}
}

func (_c *FetchRepository_FetchArchive_Call) Run(run func(ctx context.Context, spec domain.ArchiveFetch)) *FetchRepository_FetchArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ArchiveFetch))
	})
	return _c
}

func (_c *FetchRepository_FetchArchive_Call) Return(sourceDir string, err error) *FetchRepository_FetchArchive_Call {
	_c.Call.Return(sourceDir, err)
	return _c
}

func (_c *FetchRepository_FetchArchive_Call) RunAndReturn(run func(context.Context, domain.ArchiveFetch) (string, error)) *FetchRepository_FetchArchive_Call {
	_c.Call.Return(run)
	return _c
}

// FetchGit provides a mock function with given fields: ctx, spec, verbose
func (_m *FetchRepository) FetchGit(ctx context.Context, spec domain.GitFetch, verbose bool) (string, error) {
	ret := _m.Called(ctx, spec, verbose)

	if len(ret) == 0 {
		panic("no return value specified for FetchGit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GitFetch, bool) (string, error)); ok {
		return rf(ctx, spec, verbose)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GitFetch, bool) string); ok {
		r0 = rf(ctx, spec, verbose)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GitFetch, bool) error); ok {
		r1 = rf(ctx, spec, verbose)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchRepository_FetchGit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchGit'
type FetchRepository_FetchGit_Call struct {
	*mock.Call
}

// FetchGit is a helper method to define mock.On call
//   - ctx context.Context
//   - spec domain.GitFetch
//   - verbose bool
func (_e *FetchRepository_Expecter) FetchGit(ctx interface{}, spec interface{}, verbose interface{}) *FetchRepository_FetchGit_Call {
	return &FetchRepository_FetchGit_Call{Call: _e.mock.On("FetchGit", ctx, spec, verbose)}
}

func (_c *FetchRepository_FetchGit_Call) Run(run func(ctx context.Context, spec domain.GitFetch, verbose bool)) *FetchRepository_FetchGit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GitFetch), args[2].(bool))
	})
	return _c
}

func (_c *FetchRepository_FetchGit_Call) Return(sourceDir string, err error) *FetchRepository_FetchGit_Call {
	_c.Call.Return(sourceDir, err)
	return _c
}

func (_c *FetchRepository_FetchGit_Call) RunAndReturn(run func(context.Context, domain.GitFetch, bool) (string, error)) *FetchRepository_FetchGit_Call {
	_c.Call.Return(run)
	return _c
}

// NewFetchRepository creates a new instance of FetchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FetchRepository {
	mock := &FetchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
