// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/supanadit/forge/domain"

	mock "github.com/stretchr/testify/mock"
)

// ManifestRepository is an autogenerated mock type for the ManifestRepository type
type ManifestRepository struct {
	mock.Mock
}

type ManifestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ManifestRepository) EXPECT() *ManifestRepository_Expecter {
	return &ManifestRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, path
func (_m *ManifestRepository) Load(ctx context.Context, path string) (domain.Manifest, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 domain.Manifest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Manifest, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Manifest); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(domain.Manifest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ManifestRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type ManifestRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *ManifestRepository_Expecter) Load(ctx interface{}, path interface{}) *ManifestRepository_Load_Call {
	return &ManifestRepository_Load_Call{Call: _e.mock.On("Load", ctx, path)}
}

func (_c *ManifestRepository_Load_Call) Run(run func(ctx context.Context, path string)) *ManifestRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ManifestRepository_Load_Call) Return(_a0 domain.Manifest, _a1 error) *ManifestRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ManifestRepository_Load_Call) RunAndReturn(run func(context.Context, string) (domain.Manifest, error)) *ManifestRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewManifestRepository creates a new instance of ManifestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManifestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManifestRepository {
	mock := &ManifestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
